#!/usr/bin/env bash

# DO NOT EDIT THIS FILE!
#
# It's auto-generated by sonata-project/dev-kit package.

set -ev

if [ -f .travis/before_script_test.local.sh ]
then
    ./.travis/before_script_test.local.sh
fi
