rules:
    blank_line_after_directive: ~
    short_array_syntax: ~
    typo: ~
    replacement: ~
    composer_dev_option_at_the_end: ~
    yarn_dev_option_at_the_end: ~
    versionadded_directive_should_have_version: ~
    no_composer_req: ~
    no_php_open_tag_in_code_block_php_directive: ~
    blank_line_after_filepath_in_code_block: ~
    no_php_prefix_before_bin_console: ~
    use_deprecated_directive_instead_of_versionadded: ~
    no_space_before_self_xml_closing_tag: ~
    no_explicit_use_of_code_block_php: ~
    ensure_order_of_code_blocks_in_configuration_block: ~
    american_english: ~
    valid_use_statements: ~
    yaml_instead_of_yml_suffix: ~
    extend_abstract_admin: ~
    final_admin_class: ~
    final_admin_extension_classes: ~
    no_admin_yaml: ~
    no_bash_prompt: ~
    no_composer_phar: ~
    no_inheritdoc: ~

    # can be enabled when no Symfony 3.4 support anymore
    #no_app_bundle: ~
    #no_config_yaml: ~
    #kernel_instead_of_app_kernel: ~
    #no_app_console: ~
