on: [push, pull_request]

name: Lint

jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer

        runs-on: ubuntu-latest

        steps:
            - name: "Checkout"
              uses: actions/checkout@v2

            - name: "Run PHP-CS-Fixer"
              uses: docker://oskarstark/php-cs-fixer-ga:2.16.1
              with:
                  args: --ansi --verbose --diff --dry-run

    composer-normalize:
        name: composer-normalize

        runs-on: ubuntu-latest

        steps:
            - name: "Checkout"
              uses: actions/checkout@v2

            - name: "Run composer-normalize"
              uses: docker://localheinz/composer-normalize-action:0.5.2
              with:
                  args: --dry-run

    yaml-files:
        name: YAML files

        runs-on: ubuntu-latest

        steps:
            - name: "Checkout"
              uses: actions/checkout@v2

            - name: "Install Ruby 2.6"
              uses: actions/setup-ruby@v1
              with:
                  ruby-version: '2.6'

            - run: gem install yaml-lint

            - name: "Linting..."
              run: make lint-yaml

    xml-files:
        name: XML files

        runs-on: ubuntu-latest

        steps:
            - name: "Checkout"
              uses: actions/checkout@v2

            - run: sudo apt-get install libxml2-utils

            - name: "Linting..."
              run: make lint-xml
