on: [push, pull_request]
name: Quality assurance
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHPStan
        uses: "docker://oskarstark/phpstan-ga"
        env:
          REQUIRE_DEV: true
        with:
          args: analyse -c .phpstan/phpstan.neon.dist
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
